server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://identity-service:8081
          predicates:
            - Path=/auth/**,/.well-known/jwks.json
        - id: demo-service
          uri: http://demo-service:8082
          predicates:
            - Path=/demo/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://identity-service:8081/.well-known/jwks.json
