

server:
  port: 8080

gateway:
  identity-prefix: /identity/v1

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpserver:
        wiretap: true
      routes:
        - id: identity-service
          uri: http://identity-service:8081
          predicates:
            - Path=/identity/v1/**
          filters:
            - StripPrefix=2
        - id: demo-service
          uri: http://demo-service:8082
          predicates:
            - Path=/demo/**
        - id: identity-jwks
          uri: http://identity-service:8081
          predicates:
            - Path=/.well-known/jwks.json

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://gateway-service:8080/.well-known/jwks.json
