server:
  port: 8082

spring:
  application:
    name: demo-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://identity-service:8081/.well-known/jwks.json

feign:
  client:
    identity-service:
      url: http://identity-service:8081
